In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% ! important;}
div.cell.code_cell.rendered{width:100%}
div.input_prompt{padding:0px}
div.CodeMirror {font-family:Consolas ; font-size:12pt;}
div.text_cell_render.rendered_html {font-size:12pt;}
div.output {font-size:12pt; font-weight:bold}
div.input {font-family:Consolas ; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper {padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

# 데이터 비교를 위한 for문 점검

In [118]:
check_number = []
for data_idx in range(21):
    if data_idx == 0:
        for start_idx in range(3):
            check_number.append(f'{0}일')
    else:
        for udw_idx in range(3):
            check_number.append(f'{data_idx}일 {udw_idx}')

In [119]:
len(check_number)

63

# 실행코드

In [108]:
import pandas as pd

# 
data = pd.read_csv('data/주식데이터크롤링.csv')
data.head()

         날짜       종목명  종가(백만원)  거래량(천주)
0  20251222   KRX 자동차  2515.49     7222
1  20251222  KRX 헬스케어  4810.27    13195
2  20251222    KRX 건설   832.91    53960
3  20251219   KRX 자동차  2515.84    12806
4  20251219  KRX 헬스케어  4861.55    30168

In [110]:
data.sort_values(by='날짜',ascending=True, inplace=True)
data.reset_index(drop=True, inplace=True)
data

          날짜       종목명  종가(백만원)  거래량(천주)
0   20251124    KRX 건설   756.88     6081
1   20251124  KRX 헬스케어  4861.50    27673
2   20251124   KRX 자동차  2211.18     7772
3   20251125    KRX 건설   758.07     5175
4   20251125  KRX 헬스케어  4752.20    23585
..       ...       ...      ...      ...
58  20251219  KRX 헬스케어  4861.55    30168
59  20251219   KRX 자동차  2515.84    12806
60  20251222  KRX 헬스케어  4810.27    13195
61  20251222    KRX 건설   832.91    53960
62  20251222   KRX 자동차  2515.49     7222

[63 rows x 4 columns]

In [112]:
check_data = data.iloc[:,-2].copy()
KRX_items = set(data.iloc[:,1])

In [113]:
data_count = len(check_data)
KRX_count = len(KRX_items)

date_count = int(data_count/KRX_count)

In [114]:
up_down_list = []
# 전체데이터에 날짜당 아이템 갯수를 나누어 묶음들을 구함
for date_idx in range(date_count):
    # 묶음 내부의 값들의 증감치 추가
    # 첫 묶음은 비교대상이 없기에 '시작일'로 지정
    if date_idx == 0:
        for start_idx in range(KRX_count):
            up_down_list.append('시작일')
    else:
        # 현재 묶음과 이전 묶음의 각각의 아이템의 크기를 비교 
        for udw_idx in range(KRX_count):
            if check_data[date_idx*3 + udw_idx] > check_data[(date_idx-1)*3 + udw_idx]:
                up_down_list.append('증가')
            elif check_data[date_idx*3 + udw_idx] < check_data[(date_idx-1)*3 + udw_idx]:
                up_down_list.append('감소')
            else:
                up_down_list.append('변동없음')

In [73]:
len(up_down_list)

63

In [115]:
up_down_list[:10]

['시작일', '시작일', '시작일', '증가', '감소', '증가', '증가', '증가', '증가', '감소']

In [116]:
data['전일대비'] = up_down_list

In [117]:
data.head(12)

          날짜       종목명  종가(백만원)  거래량(천주) 전일대비
0   20251124    KRX 건설   756.88     6081  시작일
1   20251124  KRX 헬스케어  4861.50    27673  시작일
2   20251124   KRX 자동차  2211.18     7772  시작일
3   20251125    KRX 건설   758.07     5175   증가
4   20251125  KRX 헬스케어  4752.20    23585   감소
5   20251125   KRX 자동차  2215.05     6562   증가
6   20251126    KRX 건설   787.14     7811   증가
7   20251126  KRX 헬스케어  4873.34    24956   증가
8   20251126   KRX 자동차  2262.07    11557   증가
9   20251127    KRX 건설   783.77     8948   감소
10  20251127  KRX 헬스케어  4855.56    20680   감소
11  20251127   KRX 자동차  2296.52    14199   증가

In [121]:
data.to_csv('data/전일대비_증감치추가.csv')